name: Continuous Deployment

on:
  workflow_dispatch:
    inputs:
      git-sha:
        description: 'The short Git SHA of the S3 artifact to deploy (e.g., a3f9c12)'
        required: true
        type: string

jobs:
  lambda-cd:
    uses: vishuops0210/shared-repo/.github/workflows/cd-lambda.yml@main
    with:
      git-sha: ${{ inputs.git-sha }}
      function-name: 'bajaj-poc-lambda'
      s3-bucket-name: 'my-bajaj-artifacts-bucket'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}