name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "uat" ]

jobs:
  lambda-ci:
    uses: vishuops0210/shared-repo/.github/workflows/lambda-ci.yml@main
    with:
      function-name: 'bajaj-poc-lambda'
      s3-bucket-name: 'my-bajaj-artifacts-bucket'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
