name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "uat" ]

jobs:
  lambda-ci:
    uses: vishuops0210/shared-repo/.github/workflows/ci/lambda/python.yml@main
    with:
      version: 'v1.0.0'
      function-name: 'bajaj-poc-lambda'
      s3-bucket-name: 'my-bajaj-artifacts-bucket'
      install-command: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
      test-command: |
        pytest --cov --cov-report=xml:coverage.xml --junitxml=test-results.xml
      coverage-report-path: 'coverage.xml'
      sonar-args: '-Dsonar.python.coverage.reportPaths=coverage.xml'
      package-command: |
        mkdir package
        pip install -r requirements.txt -t package/
        cp *.py package/
        cd package
        zip -r ../deployment.zip .
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
